
language: python

branches:
  only:
    - master

script:
  - tox -e $TOX_ENV

install:
  - pip install tox

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.6
      env: TOX_ENV=py36

